name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.014'
          - '5.020'
          - '5.030'
          - '5.040'

    name: Perl ${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v7

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install Dependencies
        run: |
          perl Makefile.PL
          cpanm --installdeps .

      - name: Run Tests
        run: make test
