name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.014'
          - '5.020'
          - '5.030'
          - '5.040'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }} # https://hub.docker.com/r/perldocker/perl-tester

    name: Perl ${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v7

      - name: perl -V
        run: perl -V
      - name: Cache CPAN dependencies
        uses: actions/cache@v6
        with:
          path: ~/.cpanm
          key: ${{ runner.os }}-cpan-${{ hashFiles('**/Makefile.PL', '**/cpanfile') }}
          restore-keys: |
            ${{ runner.os }}-cpan-
      - name: Install Dependencies
        run: cpanm -v --notest --installdeps .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Regular tests
        run: make test
